# ECON 815 Problem Set \#2

## Destan Kirimhan

# Question 2. Introduction to NumPy Chapter
## Problem 1. 
### NumPy’s dot() function performs matrix multiplication. Write a function that defines the following matrices as NumPy arrays.

$$
A = \begin{bmatrix}
    3 & -1 & 4 & \\
    1 & 5 & -9
    \end{bmatrix}
$$

$$
B = \begin{bmatrix}
    2 & 6 & -5 & 3 \\
    5 & -8 & 9 & 7\\
    9 & -3 & -2 & -3\\
    \end{bmatrix}
$$

### Return the matrix product AB.

In [1]:
import numpy as np

In [2]:
def matrixmult (A, B):
    a=np.array(A)
    b=np.array(B)
    C=np.dot(a, b)
    return C

In [3]:
A = [[3,-1,4],[1,5,-9]]
B = [[2,6,-5,3],[5,-8,9,7],[9,-3,-2,-3]]

In [4]:
matrixmult(A,B)

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

## Problem 2. 
### Write a function that defines the following matrix as a NumPy array.

$$
A = \begin{bmatrix}
    3 & 1 & 4 \\
    1 & 5 & 9 \\
    -5 & 3 & 1 \\
    \end{bmatrix}
$$

### Return the matrix $$ \begin{equation} -A^3 + 9A^2 -15A \end{equation}. $$

In [5]:
def matrixpoly (A):
    a=np.array(A)
    A_sq=np.dot(a,a)
    a_sq=np.array(A_sq)
    A_cube=np.dot(a_sq,a)
    x=-15*a
    result=-1*A_cube + 9*A_sq -15*a
    return result

In [6]:
A = [[3,1,4],[1,5,9],[-5,3,1]]

In [7]:
matrixpoly(A)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Introduction to NumPy Chapter
## Problem 5. 
### Write a function that defines the following matrices as NumPy arrays.

$$
A = \begin{bmatrix}
    0 & 2 & 4 \\
    1 & 3 & 5
    \end{bmatrix}
$$

$$
B = \begin{bmatrix}
    3 & 0 & 0 \\
    3 & 3 & 0 \\
    3 & 3 & 3 \\
    \end{bmatrix}
$$

$$
C = \begin{bmatrix}
    -2 & 0 & 0 \\
    0 & -2 & 0 \\
    0 & 0 & -2 \\
    \end{bmatrix}
$$

### Use NumPy’s stacking functions to create and return the block matrix:

$$
    \begin{bmatrix}
    0 & A^T & I \\
    A & 0 & 0 \\
    B & 0 & C \\
    \end{bmatrix}
$$
### where I is the identity matrix of the appropriate size and each 0 is a matrix of all zeros, also of appropriate sizes.

In [8]:
def matrixpoly (A,B,C):
    a=np.array(A)
    b=np.array(B)
    c=np.array(C)
    a_T=np.array(np.transpose(A))
    I=np.eye((3), dtype=np.int)
    z2=np.zeros((2,2), dtype=np.int)
    z3=np.zeros((3,3), dtype=np.int)
    z23=np.zeros((2,3), dtype=np.int)
    z32=np.zeros((3,2), dtype=np.int)
    result1=np.vstack((z3,a,b))
    result2=np.vstack((a_T,z2,z32))
    result3=np.vstack((I,z23,c))
    result=np.hstack((result1,result2,result3))
    return result

In [9]:
A = [[0,2,4],[1,3,5]]
B = [[3,0,0],[3,3,0],[3,3,3]]
C = [[-2,0,0],[0,-2,0],[0,0,-2]]

In [10]:
matrixpoly(A,B,C)

array([[ 0,  0,  0,  0,  1,  1,  0,  0],
       [ 0,  0,  0,  2,  3,  0,  1,  0],
       [ 0,  0,  0,  4,  5,  0,  0,  1],
       [ 0,  2,  4,  0,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0,  0],
       [ 3,  0,  0,  0,  0, -2,  0,  0],
       [ 3,  3,  0,  0,  0,  0, -2,  0],
       [ 3,  3,  3,  0,  0,  0,  0, -2]])

# Question 1. Standard Library Chapter
## Problem 1. 
### Write a function that accepts a list of numbers as input and returns a new list with the minimum, maximum, and average of the original list (\in that order). Remember to use floating point division to calculate the average. Can you implement this function in a single line?

In [13]:
f = lambda *x: ([min(x), max(x), sum(x)/len(x)])

### To provide an example and check if the function is working properly:

In [14]:
f(1,2,3.5)

[1, 3.5, 2.1666666666666665]

## Problem 2. 

### Python has several methods that seem to change immutable objects. These methods actually work by making copies of objects. We can therefore determine which object types are mutable and which are immutable by using the equal sign and “changing” the objects. 

### >>> dict_1 = {1: 'x', 2: 'b'}       # Create a dictionary. 
### >>> dict_2 = dict_1 # Assign it a new name.
### >>> dict_2[1] = 'a' # Change the 'new' dictionary.
### >>> dict_1 == dict_2 # Compare the two names.
### True

### Since altering one name altered the other, we conclude that no copy has been made and that therefore Python dictionaries are mutable. If we repeat this process with a di↵erent type and the two names are di↵erent in the end, we will know that a copy had been made and the type is immutable. Following the example given above, determine which object types are mutable and which are immutable. Use the following operations to modify each of the given types. 

### Print a statement of your conclusions.

In [1]:
x=5
y=x
y=y+1
x==y

False

### Numbers are immutable.

In [3]:
x='Destan'
y=x
y=y+'a'
x==y

False

### Strings are immutable.

In [4]:
months = ('0','1')
months2=months
months2=months2 + ('1','1')
months==months2

False

### Tuples are immutable. 

In [5]:
dict1={1: 'x', 2: 'b'}
dict2=dict1
dict2[1]='a'
dict1==dict2

True

### Dictionaries are mutable.

In [7]:
L1 = [1, 2, 3]
L2=L1
L2.append(1)
L1==L2

True

### Lists are mutable.

## Problem 3. 
### Create a module called calculator.py. Write a function that returns the sum of two arguments, a function that returns the product of two arguments, and a function that returns the square root of a single argument. When the file is either run or imported, nothing should be executed. In your main solutions file, import your new calculator module. Using only the functions defined in the module, write a new function that calculates the length of the hypotenuse of a right triangle given the lengths of the other two sides.

In [8]:
import calculator

In [9]:
run calculator.py

In [10]:
def hypo(val1, val2):
    hypot = calculator.sq(calculator.tot(calculator.product(val1, val1), calculator.product(val2, val2)))
    return hypot

In [11]:
hypo(3, 4)

5.0

In [12]:
hypo(5, 12)

13.0

In [13]:
hypo(7, 24)

25.0

### Calculator.py
def product(val1, val2):
    prod = val1 * val2
    
    return prod
   
def tot(val1, val2):
    total = val1 + val2
    
    return total

def sq(val1):
    sqroot = val1 ** 0.5
    
    return sqroot

# Question 3. OOP

## Problem 1. Expand the Backpack class to match the following specifications.

### 1. Modify the constructor so that it accepts a name, a color, and a maximum size (in that order). Make max_size a default argument with default value 5. Store each input as an attribute. 
### 2. Modify the put() method to ensure that the backpack does not go over capacity. If the user tries to put in more than max_size items, print “No Room!” and do not add the item to the contents list. 
### 3. Add a new method called dump() that resets the contents of the backpack to an empty list. This method should not receive any arguments (except self).

class Backpack():
    
    def __init__(self, name, color, max_size=5):
        self.name = name
        self.color = color
        self.max_size = 5
        self.contents = []
       
    def put(self, item):
            if self.contents.len(item) > self.max_size:
                print('No Room!')
            else:
                self.contents.append(item)
                
    def dump(self):
        self.contents = []
       
    testpack = Backpack()
    testpack.__init__()
    testpack.put()
    testpack.dump()
                
    """
    Attributes:
         name (str): name of the backpack owner.
         color (str): color of the backpack owner.
         max_size (int): equals to 5 by default.
    """

# Problem 2.
## Create a Jetpack class that inherits from the Backpack class. 
### 1. Overwrite the constructor so that in addition to a name, color, and maximum size, it also accepts an amount of fuel. Change the default value of max_size to 2, and set the default value of fuel to 10. Store the fuel as an attribute. 
### 2. Add a fly() method that accepts an amount of fuel to be burned and decrements the fuel attribute by that amount. If the user tries to burn more fuel than remains, print “Not enough fuel!” and do not decrement the fuel.
### 3. Overwrite the dump() method so that both the contents and the fuel tank are emptied.

class Jetpack(Backpack):

    """A Jetpack object class. Inherits from the Backpack class.
       A Jetpack is smaller than a backpack and can be tied closed.
       Attributes:
           name (str): the name of the jetpack's owner.
           color (str): the color of the jetpack.
           max_size (int): the maximum number of items that can fit in the jetpack.
           contents (list): the contents of the backpack.
           fuel (int): amount of fuel it accepts. 
           closed (bool): whether or not the jetpack is tied shut.
    """
    
    def __init__(self, name, color, max_size=2, fuel=10):
        self.max_size = 2
        self.fuel = 10
        
    """Use the Backpack constructor to initialize the name, color, and max_size attributes. A jetpack only holds 2 item by default
       instead of 3.
       Inputs:
       name (str): the name of the jetpack's owner.
       color (str): the color of the jetpack.
       max_size (int): the maximum number of items that can fit in the jetpack. Defaults to 2.
       fuel (int): amount of fuel it accepts.
       Returns:
       A jetpack object with no contents.
    """
    
    Backpack.__init__(self, name, color, max_size)
    self.closed = True
        
    def fly(self, fuelburn):
            if self.fuelburn < self.fuel:
                self.fuel=self.fuel - self.fuelburn
            else: 
                print('Not enough fuel!')
                
    """Inputs:
       fuelburn (int): amount of fuel to be burned it accepts.
    """
            
    def dump(self):
        self.fuel = 0
    
    Backpack.dump(self):
    self.closed = True
